server:
  port: 4050

spring:
  profiles:
    active: dev  # 开发环境
  application:
    name: mysql-elasticsearch
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      # 只要消息抵达队列,以异步方式优先回调returnsConfirm
      mandatory: true
    listener:
      simple:
        # 消费端手动ack消息
        acknowledge-mode: manual
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: Summer15-cluster
      repositories:
        enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/wsw?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: wsw19980801
    hikari:
      minimum-idle: 5
      max-lifetime: 1800000
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#  redis:
#    host: 39.107.80.231
#    port: 6379
#    lettuce:
#      pool:
#        # 连接池最大连接数(使用负值表示没有限制) 默认为8
#        max-active: 8
#        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
#        max-wait: -1ms
#        # 连接池中的最大空闲连接 默认为8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认为 0
#        min-idle: 0
#
#redisson:
#  client:
#    address: redis://39.107.80.231:6379

management:
  endpoints:
    web:
      exposure:
        include: '*'
